algorithm: iomatch
save_dir: ./saved_models/openset_cv
save_name: wrn_28_8
resume: True
load_path: ///data1/daniya_miccai24/weighted_iomatch/IOMatch-main_isic2018/saved_models/openset_cv/WEIGHT28/model_best.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_labels: 375
batch_size: 16
eval_batch_size: 64
p_cutoff: 0.95
q_cutoff: 0.5
mb_loss_ratio: 1.0
ulb_loss_ratio: 1.0
op_loss_ratio: 1.0
use_rot: False
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_8
net_from_name: False
data_dir: '/data1/Medical/ECL/data/ISIC2018/'
dataset: isic2018_openset
train_sampler: RandomSampler
num_classes: 5
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10055
dist_backend: nccl
gpu: 2